baseURL       = "https://dwdbeauvoir.nl/"
languageCode  = "nl-nl"
title         = "D.W.D. Beauvoir"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Historie"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Bestuur"
    url     = "bestuur"
    weight  = 3
  [[menu.nav]]
    name    = "Leden"
    url     = "leden"
    weight  = 4
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "logo_beauvoir_mintgroen(1).png" # Waar staat het mapje images --> even zoeken en logo in stoppen : static/images/logo_beauvoir_mintgroen(1).png
  logo_footer = "logo_beauvoir_mintgroen(1).png"
  favicon_icon = "logo_beauvoir_mintgroen(1).png"
  favicon_shortcut_icon = "logo_beauvoir_mintgroen(1).png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "17 februari 2016"
  # Meta data
  description = "Dames Wedstrijd Dispuut Beauvoir"
  author = "Marijke, Akkie en Ilse"
  fabform  = "https://formspree.io/f/mknlqlbz" # wat doet dit

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Simone"
    placeholder_last_name         = "de Beauvoir"
    placeholder_email             = "beauvoirbestuur@gmail.com"
    # placeholder_project_type      = "Project Type" 
    # placeholder_about_the_project = "About the Project"
    send_message                  = "Verzenden"

    [[params.contactForm.projectType]]
      value = "vraag"
      title  = "Vraag"
    [[params.contactForm.projectType]]
      value = "anders"
      title  = "Anders"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Contact"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "background@600x.png"
    heading               = "D.W.D. Beauvoir"
    tagline               = "On n'existe pas sans faire"
    primary_button        = "Bekijk onze leden"
    primary_button_url    = "leden"
    secondary_button      = "Neem contact op"
    secondary_button_url  = "contact"

  [params.historie]
    read_more             = "lees meer"

  [params.leden]
    enable    = true
    title     = "Onze leden"
    subtitle  = ""
    view_project = "view project"
    more_works = "MORE WORKS"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Heb je een vraag?"
    primary_button      = "Stuur een vraag"
    primary_button_url  = "contact"
    secondary_button    = "Historie"
    secondary_button_url = "historie"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Auke Vleerstraat 99 Enschede"
      #phone   = "409-896-1444"
      email   = "beauvoirbestuur@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Historie"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Leden"
          url  = "leden"
        [[params.footer.sitemap.link]]
          name = "Bestuur"
          url  = "bestuur"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        # [[params.footer.social.link]]
        #   name = "Medium"
        #   url  = "#"
        # [[params.footer.social.link]]
        #   name = "Behance"
        #   url  = "#"
        # [[params.footer.social.link]]
        #   name = "Dribbble"
        #   url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/d.w.d.beauvoir/"
      # Footer Service
      # [params.footer.service]
      #   title       = "We help brands:"
      #   description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
      [params.footer.back_to_top]
        description = "Naar boven"
